[package]
name = "auth_with_actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-files = "0.6.6"
actix-web = "4.9.0"
cargo-files = "0.3.1"
jsonwebtoken = "9.3.0"
serde = "1.0.210"
web = "0.2.12"
